baseURL = "/"

languageCode = "en-us"
DefaultContentLanguage = "en"
title = "DBJ.Systems Experimental Knowledge Base"
theme = "docdock"
# themesdir = "../.."
pygmentsCodeFences = true
pygmentsStyle = "monokailight"



# [Languages]
# [Languages.en]
# title = "Documentation for Hugo docDock"
# weight = 1
# languageName = "English"
# 
# [Languages.fr]
# title = "Documentation du thème docDock"
# weight = 2
# languageName = "Français"




[params]
author="DBJ"
description="DBJ.Systems Knowledge Base"
editURL = "https://x.dbj.org"
showVisitedLinks = true # default is false
themeStyle = "original" # "original" or "flex" # default "flex"
themeVariant = "blue" # choose theme variant "green", "gold" , "gray", "blue" (default)
ordersectionsby = "weight" # ordersectionsby = "title"
disableHomeIcon = true # default is false
disableSearch = false # default is false
disableNavChevron = false # set true to hide next/prev chevron, default is false
highlightClientSide = false # set true to use highlight.pack.js instead of the default hugo chroma highlighter
menushortcutsnewtab = false # set true to open shortcuts links to a new tab/window
enableGitInfo = true

[outputs]
home = [ "HTML", "RSS", "JSON"]


[[menu.shortcuts]]
pre = "<h3>More</h3>"
name = "<i class='fa fa-github'></i> <label>Github repo</label>"
identifier = "kb_repo"
url = "https://github.com/dbj-systems/kb"
weight = 100

[[menu.shortcuts]] 
name = "<i class='fa fa-lightbulb-o'></i> <label>Enlight IT</label>"
identifier = "enlit"
url = "https://enlightit.rs"
weight = 100

# [[menu.shortcuts]]
# name = "<i class='fa fa-cloud-download'></i> <label>Download</label>"
# url = "https://github.com/vjeantet/hugo-theme-docdock/archive/master.zip"
# weight = 110

[[menu.shortcuts]]
name = "<i class='fa fa-bookmark'></i> <label>Hugo Documentation</label>"
identifier = "hugodoc"
url = "https://gohugo.io/"
weight = 120
