baseURL = "/"
languageCode = "en-us"
title = "DBJ.Systems Experimental Knowledge Base"

# Change the default theme to be use when building the site with Hugo
theme = "learn" 

# For search functionality
[outputs]
home = [ "HTML", "RSS", "JSON"]

[params]
author="DBJ"
description="DBJ.Systems Knowledge Base"
# https://learn.netlify.com/en/basics/style-customization/
# Change default color scheme with a variant one. Can be "red", "blue", "green".
themeVariant = "dbjsystems"
disableBreadcrumb = false
showVisitedLinks = true
disableNextPrev = true
 # When using mulitlingual website, disable the switch language button.
 disableLanguageSwitchingButton = true

[[menu.shortcuts]]
name = "MORE"
identifier = "menu_more"

[[menu.shortcuts]] 
name = "Enlight IT"
identifier = "enlit"
url = "https://enlightit.rs"
weight = 100

[[menu.shortcuts]]
name = "<i class='fas fa-tags'></i> Tags"
identifier = "tags"
url = "/tags"
weight = 130
